### ISSUE TITLE
simple deployment issue

### ISSUE THREAD

**Issue by pejotes** [open3fs/m3fs#106]
hello, I'm trying to deploy m3fs on a openstack cloud. I've created 6 machines, deployer and 5 3fs nodes. I need to use just ip connectivity, so I've selected RXE and ran prepare step.

config:
``` yaml
name: "open3fs"
workDir: "/opt/3fs"
networkType: "RXE"
nodes:
  - name: node1
    host: "192.168.1.226"
    username: "root"
  - name: node2
    host: "192.168.1.142"
    username: "root"
  - name: node3
    host: "192.168.1.185"
    username: "root"
  - name: node4
    host: "192.168.1.223"
    username: "root"
  - name: node5
    host: "192.168.1.181"
    username: "root"
services:
  client:
    nodes:
      - node1
    hostMountpoint: /mnt/3fs
  storage:
    nodes:
      - node1
      - node2
      - node3
      - node4
    diskType: "dir"
  mgmtd:
    nodes:
      - node5
  meta:
    nodes:
      - node5
      - node4
      - node3
  monitor:
    nodes:
      - node5
  fdb:
    nodes:
      - node5
      - node2
      - node1
  clickhouse:
    nodes:
      - node5
images:
  registry: ""
  3fs:
    repo: "open3fs/3fs"
    tag: "20250410-avx2"
  fdb:
    repo: "open3fs/foundationdb"
    tag: "7.3.63"
  clickhouse:
    repo: "open3fs/clickhouse"
    tag: "25.1-jammy"
```

the error during deployemnt occurs
``` output
[...]
DEBU[0039] Run command: sudo docker exec 3fs-mgmtd python3 /opt/3fs/data_placement/src/setup/gen_chain_table.py --chain_table_type CR --node_id_begin 10001 --node_id_end 10004 --num_disks_per_node 1 --num_targets_per_disk 32 --target_id_prefix 1 --chain_id_prefix 9 --incidence_matrix_path output/DataPlacementModel-v_4-b_64-r_32-k_2-λ_11-lb_1-ub_0/incidence_matrix.pickle  NODE=node5 TASK=InitUserAndChainTask
DEBU[0039] Output of `sudo docker exec 3fs-mgmtd python3 /opt/3fs/data_placement/src/setup/gen_chain_table.py --chain_table_type CR --node_id_begin 10001 --node_id_end 10004 --num_disks_per_node 1 --num_targets_per_disk 32 --target_id_prefix 1 --chain_id_prefix 9 --incidence_matrix_path output/DataPlacementModel-v_4-b_64-r_32-k_2-λ_11-lb_1-ub_0/incidence_matrix.pickle`:   NODE=node5 TASK=InitUserAndChainTask
DEBU[0039] Run command: sudo docker exec 3fs-mgmtd bash -c "/opt/3fs/bin/admin_cli --cfg /opt/3fs/etc/admin_cli.toml --config.mgmtd_client.mgmtd_server_addresses '[\"RDMA://192.168.1.181:8000\"]' --config.user_info.token AAAxedlz8QATaxns2wBsGR1q < output/create_target_cmd.txt"  NODE=node5 TASK=InitUserAndChainTask
DEBU[0039] Output of `sudo docker exec 3fs-mgmtd bash -c "/opt/3fs/bin/admin_cli --cfg /opt/3fs/etc/admin_cli.toml --config.mgmtd_client.mgmtd_server_addresses '[\"RDMA://192.168.1.181:8000\"]' --config.user_info.token AAAxedlz8QATaxns2wBsGR1q < output/create_target_cmd.txt"`: Encounter error: 7004(StorageClient::RoutingError)
./src/client/cli/admin/CreateTarget.cc:69, '_result' has error
Encounter error: 7004(StorageClient::RoutingError)
./src/client/cli/admin/CreateTarget.cc:69, '_result' has error
Encounter error: 7004(StorageClient::RoutingError)
[...]
```
the script continues and deployes the client as well, but fuse mount doesn't work like intended.
