### ISSUE TITLE
Storage install error with  diskType: "nvme"

### ISSUE THREAD

**Issue by linuxflow-hqukz** [open3fs/m3fs#114]
./m3fs -version
m3fs version v0.1.9
Git SHA: 77291de
Build At: 2025-05-20T08:18:52UTC
Go Version: go1.24.1
Go OS/Arch: linux/amd64

nvme list 
Node                  SN                   Model                                    Namespace Usage                      Format           FW Rev  
--------------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1          VMware NVME_0000     VMware Virtual NVMe Disk                 1         274.88  GB / 274.88  GB    512   B +  0 B   1.3

### 

```
name: "open3fs"
workDir: "/opt/3fs"
# networkType configure the network type of the cluster, can be one of the following:
# -    IB: use InfiniBand network protocol
# -  RDMA: use RDMA network protocol
# - ERDMA: use aliyun ERDMA as RDMA network protocol
# -   RXE: use Linux rxe kernel module to mock RDMA network protocol
networkType: "RXE"
nodes:
  - name: 3fs01
    host: "172.16.2.221"
    username: "root"
    password: ""
  - name: 3fs02
    host: "172.16.2.222"
    username: "root"
    password: ""
  - name: 3fs03
    host: "172.16.2.223"
    username: "root"
    password: ""
  - name: 3fs-monitor
    host: "172.16.2.220"
    username: "root"
    password: ""
services:
  client:
    nodes: 
      - 3fs-monitor
    hostMountpoint: /mnt/3fs
  storage:
    nodes: 
      - 3fs01
      - 3fs02
      - 3fs03
    # diskType configure the disk type of the storage node to use, can be one of the following:
    # - nvme: NVMe SSD
    # - dir: use a directory on the filesystem
    diskType: "nvme"
  mgmtd:
    nodes: 
      - 3fs01
      - 3fs02
      - 3fs03
  meta:
    nodes: 
      - 3fs01
      - 3fs02
      - 3fs03
  monitor:
    nodes:
      - 3fs-monitor
  fdb:
    nodes: 
      - 3fs01
      - 3fs02
      - 3fs03
  clickhouse:
    nodes: 
      - 3fs-monitor
    # Database name for Clickhouse
    db: "3fs"
    # User for Clickhouse authentication
    user: "default"
    # Password for Clickhouse authentication
    password: "password"
    # TCP port for Clickhouse
    tcpPort: 8999
  grafana:
    nodes: 
      - 3fs-monitor
    # TCP port for Grafana
    port: 3000
images:
  registry: ""
  3fs:
    # If you want to run on environment not support avx512, add -avx2 to the end of the image tag, e.g. 20250410-avx2.
    repo: "open3fs/3fs"
    tag: "20250410-avx2"
  fdb: 
    repo: "open3fs/foundationdb"
    tag: "7.3.63"
  clickhouse:
    repo: "open3fs/clickhouse"
    tag: "25.1-jammy"
  grafana:
    repo: "open3fs/grafana"
    tag: "12.0.0"
```

When I use “diskType: ‘nvme’” to create storage, an error occurs as follows. However, no error occurs when using “dir”.

INFO[0020] Running task CreateStorageServiceTask        
INFO[0021] Start to run script disk_tool.sh on node      NODE=3fs02 TASK=CreateStorageServiceTask
INFO[0021] Start to run script disk_tool.sh on node      NODE=3fs03 TASK=CreateStorageServiceTask
INFO[0021] Start to run script disk_tool.sh on node      NODE=3fs01 TASK=CreateStorageServiceTask
INFO[0021] Scp /tmp/remote-run-script.q7bge1/tmp_script.sh to /tmp/tmp.ID0HYUuDII  NODE=3fs02 TASK=CreateStorageServiceTask
INFO[0021] Run disk_tool.sh with [/opt/3fs/storage 1 nvme prepare]  NODE=3fs02 TASK=CreateStorageServiceTask
INFO[0021] Scp /tmp/remote-run-script.9rOrMI/tmp_script.sh to /tmp/tmp.xoJ0QTKE4k  NODE=3fs03 TASK=CreateStorageServiceTask
INFO[0021] Run disk_tool.sh with [/opt/3fs/storage 1 nvme prepare]  NODE=3fs03 TASK=CreateStorageServiceTask
INFO[0021] Scp /tmp/remote-run-script.ETpB3V/tmp_script.sh to /tmp/tmp.CXTjte1bCo  NODE=3fs01 TASK=CreateStorageServiceTask
INFO[0021] Run disk_tool.sh with [/opt/3fs/storage 1 nvme prepare]  NODE=3fs01 TASK=CreateStorageServiceTask
2025/05/22 11:29:45 create cluster: run task CreateStorageServiceTask: run `sudo bash /tmp/tmp.ID0HYUuDII /opt/3fs/storage 1 nvme prepare` failed: Process exited with status 127

Is the error coming from the disk_tool.sh script? When I place this script in the meta directory and run it, bash disk_pool.sh /opt/3fs/storage 1 nvme prepare . throw an error: disk_pool.sh: line 67: mkfs.xfs: command not found
