### ISSUE TITLE
Consider integrating open3fs into K8s ?

### ISSUE THREAD

**Issue by linuxflow-hqukz** [open3fs/m3fs#116]
This article , Setup 3FS on Kubernetes.
https://github.com/AliyunContainerService/alibabacloud-3FS/blob/main/deploy/container/README.md

**Comment by diabloneo** [comment]
We considered this when we started this project. We found that using k8s brings a problem about RDMA network: **the pod of a service must be able to access a RDMA nic**. To achieve this, you can use NVIDIA network-operator or DaoCloud Spiderpool to pass an additional RDMA NIC dedicatedly to a pod. But, in a on-prem environment, each server has limited number of physical NIC cards, which means in most cases every server can only run one 3FS service because it will use all RDMA NIC on that server.

Back to this Aliyun's solution, the reason they can deploy 3FS on ACK (Alibaba Cloud Container Service For Kubernetes) without worrying this problem is because **ACK can provide ERDMA resource for each pod**. Take a look at the resources section of the yaml files, pay attention to the **aliyun/erdma** configuration:

```
    spec:
      containers:
      - name: mgmtd
        image: registry-vpc.cn-beijing.aliyuncs.com/huweiwen-test/3fs-mgmtd:dev
        imagePullPolicy: Always
        args:
        - --cfg=/etc/mgmtd/mgmtd_main.toml
        - --app_config.node_id=$(POD_INDEX)
        - --launcher_config.allow_dev_version=true # FIXME
        - --launcher_config.cluster_id={{.Values.clusterID}}
        resources:
          requests:
            aliyun/erdma: "1"
            memory: "512Mi"
            cpu: "500m"
          limits:
            aliyun/erdma: "1"
            memory: "2Gi"
            cpu: "2"
```

So, my opinions now is: If you want to deploy 3FS in a on-prem environment, I prefer not introduce k8s until the k8s platform provides similar network features like ACK's ERDMA.
