### ISSUE TITLE
Deployment error when setting 3fs replica to 1

### ISSUE THREAD

**Issue by feeyman** [open3fs/m3fs#95]
When setting the 3fs replica to 1, regardless of the number of storage nodes, an error will be reported as follows:

![Image](https://github.com/user-attachments/assets/f0cf801a-75c7-4fd0-9653-6bf5965ac224)

The configuration file is as follows：
```
name: "open3fs"
workDir: "/opt/3fs"
networkType: "IB"
logLevel: "INFO"
ui:
  taskInfoColor: "magenta"
nodes:
  - name: cache-01
    host: "192.168.0.233"
    username: "root"
    password: "passwd"
  - name: cache-02
    host: "192.168.0.234"
    username: "root"
    password: "passwd"
  - name: cache-03
    host: "192.168.0.235"
    username: "root"
    password: "passwd"

services:
  client:
    nodes:
      - cache-01
      - cache-02
      - cache-03
    hostMountpoint: /mnt/3fs
  storage:
    nodes:
      - cache-02
      - cache-03
    # diskType configure the disk type of the storage node to use, can be one of the following:
    # - nvme: NVMe SSD
    # - dir: use a directory on the filesystem
    diskType: "nvme"
    diskNumPerNode: 11
    replicationFactor: 1   ##默认副本数是2
  mgmtd:
    nodes:
      - cache-01
  meta:
    nodes:
      - cache-01
      - cache-02
      - cache-03
  monitor:
    nodes:
      - cache-01
  fdb:
    nodes:
      - cache-01
      - cache-02
      - cache-03
  clickhouse:
    nodes:
      - cache-01
images:
  registry: ""
  3fs:
    repo: "open3fs/3fs"
    tag: "20250329"
  fdb:
    repo: "open3fs/foundationdb"
    tag: "7.3.63"
  clickhouse:
    repo: "open3fs/clickhouse"
    tag: "25.1-jammy"
```
